[package]
name = "fastfifo"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["into", "from"] }
paste = "1.0.15"
fastfifoprocmacro = { git = "https://github.com/Orkking2/FastFifoProcMacro.git" }

[dev-dependencies]
